// Anker-Events: die wichtigsten JÄHRLICH wiederkehrenden Highlights im Land
// Salzburg für unsere Zielgruppe (junge Locals 18–35 + junge Reisende 18–40).
//
// ZWECK: reine ERINNERUNG/Checkliste, damit die KI-Wochenrecherche kein bekanntes
// Groß-Event ÜBERSIEHT. Diese Liste enthält BEWUSST KEINE konkreten Datteln/Uhrzeiten
// – die variieren jährlich, Events können verschoben/eingestellt werden. Das exakte
// Datum + die Uhrzeit werden in der Wochenrecherche IMMER live über die offizielle
// Quelle (url) verifiziert; nur dann wird ein Anker übernommen (siehe event-research.ts).
//
// Pflege: gelegentlich prüfen, ob ein Event noch läuft / umbenannt wurde. `note`
// markiert Sonderfälle (nur alle 2 Jahre, rotierender Ort etc.).
//
// Framework-unabhängig (kein Server-Import) -> überall nutzbar.

import type { EventCategory } from "./events-format";

export type AnchorEvent = {
  key: string;
  name: string;
  category: EventCategory;
  region: string; // grob: "Stadt Salzburg" | "Flachgau" | ... | "ganzes Land"
  months: number[]; // Monate, in denen es typischerweise stattfindet (1–12)
  timing: string; // Zeitfenster-Hinweis in Worten (NICHT als Beleg)
  url: string; // offizielle Quelle zum Verifizieren des echten Datums
  free: "ja" | "nein" | "teils"; // Eintritt gratis?
  why: string; // 1 Satz: warum die Zielgruppe das nicht verpassen will
  note?: string; // Vorbehalt (z.B. „nur alle 2 Jahre", „Ort rotiert")
};

export const ANCHOR_EVENTS: AnchorEvent[] = [
  {
    key: "salzburger-festspiele",
    name: "Salzburger Festspiele",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [7, 8],
    timing: "meist Mitte Juli–Ende August (dazu Pfingstfestspiele Ende Mai)",
    url: "https://www.salzburgerfestspiele.at/",
    free: "nein",
    why: "Weltgrößtes Klassik-/Theaterfestival vor der Haustür – Jedermann, Oper, Weltstars, plus viel Gratis-Randprogramm.",
  },
  {
    key: "siemens-festspiel-naechte",
    name: "Siemens Fest>Spiel>Nächte",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [7, 8],
    timing: "während der Festspiele, täglich am Kapitelplatz",
    url: "https://www.siemens.com/at/de/unternehmen/stories/fest-spiel-naechte.html",
    free: "ja",
    why: "Gratis Opern-/Konzert-Public-Viewing auf Riesen-LED-Wand mit Festungsblick – Festspiel-Feeling ohne Ticketpreis.",
  },
  {
    key: "jung-und-jeder",
    name: "jung & jede*r (Festspiele-Jugendprogramm)",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [7, 8],
    timing: "Hauptprogramm während der Sommerfestspiele (Juli/August)",
    url: "https://www.salzburgerfestspiele.at/jung-jeder",
    free: "teils",
    why: "Bis zu 90 % Rabatt für unter 27-Jährige plus gratis Mitmach-Formate – günstigster Zugang zu den Festspielen.",
  },
  {
    key: "mozartwoche",
    name: "Mozartwoche",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [1],
    timing: "Ende Jänner rund um Mozarts Geburtstag",
    url: "https://mozarteum.at/mozartwoche",
    free: "nein",
    why: "Dichteste Mozart-Woche der Welt in seiner Geburtsstadt – Weltklasse-Ensembles, dazu Kino & Pub-Quiz.",
  },
  {
    key: "sommerszene",
    name: "Sommerszene (SZENE Salzburg)",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [6],
    timing: "meist Juni",
    url: "https://www.szene-salzburg.net/sommerszene",
    free: "nein",
    why: "Internationaler zeitgenössischer Tanz & Performance – das avantgardistische Gegenprogramm zur Klassik-Stadt.",
  },
  {
    key: "jazz-and-the-city",
    name: "Jazz&TheCity",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [10],
    timing: "Mitte Oktober",
    url: "https://salzburg-altstadt.at/de/salzburgjazz",
    free: "ja",
    why: "~80 Gratis-Konzerte (Jazz, Global Groove, Electronic) in Clubs & Höfen der Altstadt – Festival-Hopping ohne Ticket.",
  },
  {
    key: "live-in-salzburg",
    name: "Live in Salzburg",
    category: "party",
    region: "Stadt Salzburg",
    months: [7, 8],
    timing: "Open-Air-Konzerttage im Volksgarten, meist Ende August",
    url: "https://www.stadt-salzburg.at/liveinsalzburg",
    free: "ja",
    why: "Gratis Open-Air-Konzerte, DJ-Contest & Sommerkino im Volksgarten – das kostenlose Sommer-Line-up der Stadt.",
  },
  {
    key: "sternenkino-salzburg",
    name: "Sternenkino Salzburg",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [6, 7],
    timing: "Ende Juni–Anfang Juli, Open-Air am Kapitelplatz",
    url: "https://sternenkino-salzburg.at/",
    free: "ja",
    why: "Gratis Open-Air-Kino am Kapitelplatz mit Festungsblick – Klassiker & Newcomer in lauen Sommernächten.",
  },
  {
    key: "pride-festival-salzburg",
    name: "Pride Festival Salzburg (vormals CSD)",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [8, 9],
    timing: "Ende August–Anfang September, Parade meist Anfang September",
    url: "https://www.queersalzburg.at/",
    free: "teils",
    why: "Zehn Tage buntes queeres Programm mit ~30 Events, großer Pride-Parade und Pride-Night in der ARGEkultur.",
  },
  {
    key: "rupertikirtag",
    name: "Salzburger Rupertikirtag",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [9],
    timing: "Ende September rund um den Rupertitag (24.9.)",
    url: "https://www.salzburg-altstadt.at/de/rupertikirtag",
    free: "ja",
    why: "Größter Altstadt-Kirtag mit 120+ Attraktionen, Fahrgeschäften & Standln über die Domplätze – Volksfest mitten in der Stadt.",
  },
  {
    key: "salzburger-dult",
    name: "Salzburger Dult",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [5],
    timing: "Frühlings-Volksfest rund um Pfingsten im Mai (Messezentrum)",
    url: "https://www.dult.at/de/",
    free: "ja",
    why: "Westösterreichs größtes Volksfest mit Vergnügungspark, Dult-Stadl, Live-Musik & Clubbings – gratis Eintritt.",
  },
  {
    key: "stadtfest-salzburg",
    name: "Stadtfest Salzburg",
    category: "party",
    region: "Stadt Salzburg",
    months: [6],
    timing: "Wochenende Ende Juni, Altstadt",
    url: "https://stadtfest-salzburg.at/",
    free: "ja",
    why: "Autofreie Open-Air-Bühne mit ~25 Bühnen, Live-Bands, DJs & Streetfood – jung, gratis, mittendrin.",
  },
  {
    key: "christkindlmarkt-salzburg",
    name: "Salzburger Christkindlmarkt (Dom-/Residenzplatz)",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [11, 12, 1],
    timing: "Advent bis Neujahr",
    url: "https://christkindlmarkt.co.at/",
    free: "ja",
    why: "Klassischer Adventmarkt vor dem Dom mit Punsch, Turmblasen, Chören & Krampusläufen – der Weihnachtstreffpunkt der Stadt.",
    note: "Dauer-Markt: NICHT pro Tag listen – nur konkrete Termine/Specials (Turmblasen, Krampuslauf) oder 1× als ganztägiger Hinweis.",
  },
  {
    key: "hellbrunner-adventzauber",
    name: "Hellbrunner Adventzauber",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [11, 12],
    timing: "Advent bis Heiligabend, Schloss Hellbrunn",
    url: "https://www.hellbrunneradventzauber.at/",
    free: "teils",
    why: "Stimmungsvoller Adventmarkt am Schloss mit riesigem Christbaum – abends gratis, sonst mit Getränkegutschein.",
    note: "Dauer-Markt: NICHT pro Tag listen.",
  },
  {
    key: "sternadvent-salzburg",
    name: "Sternadvent (Sternarkaden)",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [11, 12, 1],
    timing: "Advent bis Dreikönig, Sternarkaden der Altstadt",
    url: "https://www.sternadvent.at/",
    free: "ja",
    why: "Kuratierter, feiner Adventmarkt in den Sternarkaden – kleiner und weniger touristisch als die Domplätze.",
    note: "Dauer-Markt: NICHT pro Tag listen.",
  },
  {
    key: "winterfest-salzburg",
    name: "Winterfest – Festival für zeitgenössischen Zirkus",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [11, 12, 1],
    timing: "Advent bis Dreikönig, Zeltstadt im Volksgarten",
    url: "https://www.winterfest.at/",
    free: "nein",
    why: "Größtes Festival für Neuen Circus im deutschsprachigen Raum – die richtig gute Alternative zum Adventmarkt.",
  },
  {
    key: "electric-love",
    name: "Electric Love Festival",
    category: "party",
    region: "Flachgau",
    months: [7],
    timing: "Anfang/Mitte Juli (Do–Sa), Salzburgring Plainfeld",
    url: "https://www.electriclove.at/",
    free: "nein",
    why: "Österreichs größtes EDM-Festival mit Weltklasse-DJs & gewaltiger Mainstage – der Party-Fixpunkt des Sommers.",
  },
  {
    key: "jazzfestival-saalfelden",
    name: "Jazzfestival Saalfelden",
    category: "kultur",
    region: "Pinzgau",
    months: [8, 1],
    timing: "Haupt: Ende August; zusätzlich Winter-Edition im Jänner",
    url: "https://www.jazzsaalfelden.com/",
    free: "teils",
    why: "Weltklasse-Jazz & Avantgarde mit vielen kostenlosen Open-Air-Bühnen in der Stadt und Sessions in den Bergen.",
  },
  {
    key: "bergfestival-saalbach",
    name: "BERGFESTival Saalbach",
    category: "party",
    region: "Pinzgau",
    months: [12],
    timing: "Anfang Dezember (Fr–So), Saalbach-Hinterglemm",
    url: "https://www.berg-festival.com/",
    free: "nein",
    why: "Ski, Après-Ski & Live-Bands (Punk/Ska/Indie/Brass) auf dem Berg – Winterurlaub und Festival in einem.",
  },
  {
    key: "rave-on-snow",
    name: "Rave On Snow",
    category: "party",
    region: "Pinzgau",
    months: [12],
    timing: "Mitte Dezember (Do–So), Saalbach-Hinterglemm",
    url: "https://raveonsnow.com/",
    free: "nein",
    why: "Elektro-Winterrave mit 70+ DJs auf bis zu 12 Floors – tagsüber Ski, nachts durchtanzen in Alpenkulisse.",
  },
  {
    key: "mtb-weltcup-leogang",
    name: "UCI Mountainbike Weltcup Leogang",
    category: "sport",
    region: "Pinzgau",
    months: [6],
    timing: "meist Mitte Juni, ein Wochenende, Bikepark Leogang",
    url: "https://www.mtb-weltcup.at/en",
    free: "teils",
    why: "Weltklasse-Downhill & Cross-Country im Bikepark Leogang – actionreiches Sommer-Highlight für ein junges Publikum.",
  },
  {
    key: "salzburg-trailrunning-festival",
    name: "Salzburg Trailrunning Festival",
    category: "sport",
    region: "Stadt Salzburg",
    months: [10],
    timing: "meist letztes Oktober-Wochenende (Nightrun über Festung & Gaisberg)",
    url: "https://www.trailrunning-festival.at/de/",
    free: "teils",
    why: "Urbanes Trail-Festival mit Nachtlauf über Festung und Gaisberg – Zuschauen gratis.",
  },
  {
    key: "nachtslalom-flachau",
    name: "FIS Ski-Weltcup Damen-Nachtslalom Flachau",
    category: "sport",
    region: "Pongau",
    months: [1],
    timing: "Damen-Nachtslalom unter Flutlicht, Anfang/Mitte Jänner",
    url: "https://www.skiweltcup-flachau.at/",
    free: "nein",
    why: "Flutlicht-Nachtslalom mit Après-Ski-Stimmung & Ö3-DJ – die lauteste Weltcup-Party im Land.",
  },
  {
    key: "vierschanzentournee-bischofshofen",
    name: "Vierschanzentournee Bischofshofen (Dreikönigsspringen)",
    category: "sport",
    region: "Pongau",
    months: [1],
    timing: "immer am Dreikönigstag (6. Jänner)",
    url: "https://www.vierschanzentournee.com/bischofshofen/",
    free: "nein",
    why: "Das große Skisprung-Finale der Tournee mit ~25.000 Fans – Gänsehaut-Event zum Jahresauftakt.",
  },
  {
    key: "ski-weltcup-zauchensee",
    name: "FIS Ski-Weltcup Damen Zauchensee (Speed)",
    category: "sport",
    region: "Pongau",
    months: [1],
    timing: "Damen-Abfahrt/Super-G, meist Mitte Jänner",
    url: "https://www.zauchensee.at/de/audi-fis-ski-weltcup-altenmarkt-zauchensee.html",
    free: "teils",
    why: "Damen-Speed-Klassiker auf der Kälberloch-Abfahrt – hochkarätiger Weltcup in Ski amadé.",
    note: "NICHT jährlich – nur alle 2 Jahre (biennal); in vielen Saisonen NICHT im Kalender. Vorab prüfen, ob heuer Austragungsjahr.",
  },
  {
    key: "snowboard-weltcup-gastein",
    name: "FIS Snowboard-Alpin-Weltcup Bad Gastein",
    category: "sport",
    region: "Pongau",
    months: [1],
    timing: "Parallelslalom unter Flutlicht, Mitte Jänner",
    url: "https://www.gasteinertal.com/snowboard-weltcup/",
    free: "ja",
    why: "Flutlicht-Parallelslalom mitten im Ort mit Live-Musik & After-Race-Party – gratis, jung, Snowboard statt Ski.",
    note: "Snowboard-Weltcup (NICHT der klassische Ski-Weltcup).",
  },
  {
    key: "winter-opening-flachau",
    name: "Winter Opening Flachau (Ski-Opening mit Konzert)",
    category: "party",
    region: "Pongau",
    months: [12],
    timing: "Saisoneröffnung, erstes Dezember-Wochenende",
    url: "https://www.flachau.com/",
    free: "teils",
    why: "Ski-Opening mit Skitest und großen Abend-Konzerten (z.B. Gabalier, DJ Ötzi, Nockis) – Partystart in den Winter.",
    note: "Abend-Konzerte ticketpflichtig; nur der Skitest tagsüber ist gratis.",
  },
  {
    key: "art-on-snow-gastein",
    name: "Art on Snow Gastein",
    category: "kultur",
    region: "Pongau",
    months: [1, 2],
    timing: "Schnee-/Eiskunst-Festival, Ende Jänner–Anfang Februar",
    url: "https://www.gasteinertal.com/art-on-snow/",
    free: "teils",
    why: "Eines der größten Schnee-/Eiskunst-Festivals der Alpen – begehbare Skulpturenwelt im ganzen Tal.",
  },
  {
    key: "ironman-703-zell-am-see",
    name: "IRONMAN 70.3 Zell am See-Kaprun",
    category: "sport",
    region: "Pinzgau",
    months: [8],
    timing: "Halbdistanz-Triathlon, meist Ende August",
    url: "https://www.zellamsee-kaprun.com/en/events/ironman",
    free: "teils",
    why: "Triathlon-Spektakel mit Schwimmen im Zeller See vor Gletscher-Kulisse – Zuschauen gratis.",
  },
  {
    key: "mozart-100-utmb",
    name: "mozart 100 by UTMB (Salzburg Ultra Trail)",
    category: "sport",
    region: "Flachgau",
    months: [5, 6],
    timing: "Ultra-Trail (12–120 km), meist Ende Mai/Anfang Juni, Fuschlseeregion",
    url: "https://mozart.utmb.world/",
    free: "teils",
    why: "UTMB-Ultratrail rund um Fuschl- und Wolfgangsee – Distanzen für Einsteiger bis Ultra.",
  },
  {
    key: "stadtfest-hallein",
    name: "Stadtfest Hallein",
    category: "party",
    region: "Tennengau",
    months: [6],
    timing: "ein Tag Ende Juni, Altstadt Hallein",
    url: "https://www.hallein.com/",
    free: "ja",
    why: "Urbanes Ein-Tages-Festival mit freiem Eintritt & internationalem Line-up – das Party-Highlight im Tennengau.",
  },
  {
    key: "krampuslauf-hallein",
    name: "Halleiner Krampuslauf (Igonta Pass)",
    category: "tradition",
    region: "Tennengau",
    months: [11, 12],
    timing: "immer am 1. Adventsonntag, Altstadt Hallein",
    url: "https://www.hallein.com/",
    free: "teils",
    why: "Einer der größten Krampusläufe des Landes mit 600+ Krampussen durch die enge Altstadt – Gänsehaut pur.",
    note: "Kleiner Unkostenbeitrag (~2 €); 2025 abgesagt, Neuplanung 2026 – vorab prüfen.",
  },
  {
    key: "krampuslauf-grossgmain",
    name: "Krampuslauf Großgmain",
    category: "tradition",
    region: "Flachgau",
    months: [12],
    timing: "um den 5. Dezember (Nikolaus-Vorabend), abends",
    url: "https://www.grossgmain.at/",
    free: "ja",
    why: "Bekannter Flachgauer Krampuslauf mit allen Passen & Party – Brauchtum direkt an der Stadtgrenze.",
  },
  {
    key: "pongauer-perchtenlauf",
    name: "Großer Pongauer Perchtenlauf",
    category: "tradition",
    region: "Pongau",
    months: [12, 1],
    timing: "in den Rauhnächten (21. Dezember–6. Jänner)",
    url: "https://www.gauverband-pongau.at/",
    free: "ja",
    why: "Größter Perchtenlauf im Land mit ~400 Mitwirkenden (Schön- & Schiachperchten) – archaisches Jahreswechsel-Brauchtum.",
    note: "Austragungsort ROTIERT jährlich (Altenmarkt / Bischofshofen / Gastein / St. Johann) – Ort & Termin vorab prüfen.",
  },
  {
    key: "samson-umzuege-lungau",
    name: "Samsonumzüge im Lungau",
    category: "tradition",
    region: "Lungau",
    months: [6, 7, 8, 9],
    timing: "mehrere Festtage im Sommer/Frühherbst, ~10 Lungauer Orte",
    url: "https://www.salzburgerland.com/de/magazin/samsonumzuege-riesen-im-lungau-unterwegs/",
    free: "ja",
    why: "Bis zu 7 m hohe, tanzende Riesenfiguren durch die Dörfer – UNESCO-Kulturerbe, eines der spektakulärsten Brauchtümer.",
    note: "Mehrere Orte & Termine (Tamsweg, Mauterndorf, St. Andrä …) – konkreten Ort/Termin prüfen.",
  },
  {
    key: "prangstangen-lungau",
    name: "Prangstangen-Prozession Zederhaus & Muhr",
    category: "tradition",
    region: "Lungau",
    months: [6],
    timing: "Zederhaus am 24. Juni, Muhr am 29. Juni",
    url: "https://www.muhr-tourismus.at/brauchtum/prangstangen/",
    free: "ja",
    why: "6–8 m hohe, mit zehntausenden Blumen umwundene Stangen (~85 kg) – einzigartiges Lungauer UNESCO-Brauchtum.",
  },
  {
    key: "maibaum-salzburg",
    name: "Maibaumaufstellen",
    category: "tradition",
    region: "ganzes Land",
    months: [4, 5],
    timing: "rund um den 1. Mai (teils Vorabend 30. April), fast jede Gemeinde",
    url: "https://www.salzburgerland.com/de/",
    free: "ja",
    why: "Muskelkraft, Blasmusik & Bier: gemeinsames Aufstellen des geschmückten Maibaums – der geselligste Frühlings-Brauch.",
    note: "Kein einzelnes Hauptfest – konkretes, benanntes Gemeinde-Maifest mit Datum/Uhrzeit suchen.",
  },
  {
    key: "seefest-zell-am-see",
    name: "Seefest Zell am See",
    category: "tradition",
    region: "Pinzgau",
    months: [7, 8],
    timing: "zwei Termine im Hochsommer (Air-/Wassershow, Feuerwerk)",
    url: "https://www.zellerseefest.at/",
    free: "teils",
    why: "Größtes Seefest im Pinzgau mit Flying-Bulls-Airshow, Live-Musik & Feuerwerk über dem See – Sommerabend-Tradition.",
  },
  {
    key: "almabtrieb-maishofen",
    name: "Almabtrieb & Hoffest Kammererbauer Maishofen",
    category: "tradition",
    region: "Pinzgau",
    months: [9],
    timing: "Bauernherbst, meist Mitte/Ende September bei Schloss Kammer",
    url: "https://www.maishofen.com/",
    free: "ja",
    why: "Geschmücktes Vieh zieht von der Alm ins Tal, Hoffest mit Musik & Schmankerln – ein konkreter Almabtrieb statt Bauernherbst-Slogan.",
  },
  {
    key: "silvester-altstadt-salzburg",
    name: "Silvester in der Salzburger Altstadt",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [12, 1],
    timing: "Silvesternacht 31. Dezember, Ausklang am Neujahrstag",
    url: "https://www.salzburg.info/de/salzburg/silvester",
    free: "ja",
    why: "Gratis Open-Air mit Live-Bands, Feuerwerk von der Festung und dem großen Neujahrswalzer am Domplatz – Treffpunkt statt teurem Club.",
    note: "Privates Feuerwerk/Böller im Stadtgebiet verboten; öffentlicher Platz, kein Ticket.",
  },
  {
    key: "stille-nacht-gedenkfeier-oberndorf",
    name: "Stille-Nacht-Gedenkfeier Oberndorf",
    category: "tradition",
    region: "Flachgau",
    months: [12],
    timing: "Heiliger Abend, 24. Dezember am späten Nachmittag",
    url: "https://www.oberndorf.salzburg.at/Traditionelle_Stille-Nacht-Gedenkfeier",
    free: "ja",
    why: "Weltberühmte, gratis Gedenkfeier vor der Stille-Nacht-Kapelle – ein stimmungsvolles Ritual am 24.12., das man einmal live erlebt haben sollte.",
    note: "Sehr besinnlich, kein Party-Format; wird auch per Livestream übertragen.",
  },
  {
    key: "aperschnalzen-rupertigau",
    name: "Aperschnalzen / Rupertigau-Preisschnalzen",
    category: "tradition",
    region: "Flachgau",
    months: [1, 2],
    timing: "zwischen Dreikönig und Faschingsdienstag (Jänner/Februar)",
    url: "https://www.schnalzen.de/termine/",
    free: "teils",
    why: "Lautes, archaisches Winterbrauchtum (Goaßl-Schnalzen zum Winteraustreiben) im Flachgau, ohne Touristen-Inszenierung.",
    note: "Preisschnalzen am Feld frei zuschaubar, begleitendes Festzelt kostet Eintritt; dezentraler, grenzüberschreitender Brauch an wechselnden Orten.",
  },
  {
    key: "lange-nacht-der-museen-salzburg",
    name: "ORF-Lange Nacht der Museen",
    category: "kultur",
    region: "ganzes Land",
    months: [10],
    timing: "erstes Oktober-Wochenende, Samstagabend bis Mitternacht",
    url: "https://langenacht.orf.at/state/bl/salzburg",
    free: "nein",
    why: "Ein Ticket, dutzende Museen & Galerien bis Mitternacht plus Shuttle – günstiger Kultur-Marathon für einen Abend mit Freunden.",
    note: "Bundesweites Sammelticket; Schwerpunkt Stadt Salzburg.",
  },
  {
    key: "lange-nacht-der-kirchen-salzburg",
    name: "Lange Nacht der Kirchen",
    category: "kultur",
    region: "ganzes Land",
    months: [5, 6],
    timing: "ein Freitagabend Ende Mai/Anfang Juni",
    url: "https://www.langenachtderkirchen.at/dioezesen-seiten/salzburg/",
    free: "ja",
    why: "Gratis Konzerte, Lesungen, Turmbesteigungen und Nachtführungen an sonst geschlossenen Orten – kulturelle Entdeckungstour, längst über Religion hinaus.",
    note: "Landesweit rund 50 Standorte. ACHTUNG: Erzdiözese Salzburg 2026 ausgesetzt – vorab prüfen, ob heuer teilgenommen wird.",
  },
  {
    key: "salzburg-marathon",
    name: "Salzburg Marathon (Lauffestspiele)",
    category: "sport",
    region: "Stadt Salzburg",
    months: [5],
    timing: "ein Mai-Wochenende (Nightrun Samstag, Hauptläufe Sonntag)",
    url: "https://salzburg-marathon.at/",
    free: "teils",
    why: "Lauffest quer durch die Altstadt mit Start auf der Staatsbrücke – Zuschauen gratis, Distanzen vom Nightrun bis Marathon.",
    note: "Selbes Wochenende: Salzburger Frauenlauf und Nightrun als eigene Bewerbe.",
  },
  {
    key: "trumer-triathlon",
    name: "Trumer Triathlon",
    category: "sport",
    region: "Flachgau",
    months: [7],
    timing: "ein Juli-Wochenende (Fr–So) am Trumer See",
    url: "https://www.trumer-triathlon.at/",
    free: "teils",
    why: "Sommerlicher Seen-Triathlon im Salzburger Seenland mit Volksfest-Stimmung an der Strecke – Zuschauen gratis, auch zum Mitmachen.",
    note: "Sieben Bewerbe inkl. Kinder- und Funtriathlon.",
  },
  {
    key: "wolfgangseelauf",
    name: "Internationaler Wolfgangseelauf",
    category: "sport",
    region: "Flachgau",
    months: [10],
    timing: "drittes Oktober-Wochenende rund um den Wolfgangsee",
    url: "https://www.wolfgangseelauf.at/",
    free: "teils",
    why: "Österreichs größter Landschaftslauf einmal rund um den See – riesige Kulisse, Zuschauen gratis, Bewerbe von 5 km bis Marathon.",
    note: "Grenzüberschreitend: Start/Ziel St. Gilgen (Flachgau), Teil über St. Wolfgang (OÖ).",
  },
  {
    key: "literaturfest-salzburg",
    name: "Literaturfest Salzburg",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [5],
    timing: "fünf Tage im Mai, über die ganze Stadt verteilt",
    url: "https://www.literaturfest-salzburg.at/",
    free: "teils",
    why: "Lesungen, literarische Spaziergänge und Performances an ungewöhnlichen Orten – lockeres, stadtweites Literaturfestival statt steifer Hochkultur.",
  },
  {
    key: "rauriser-literaturtage",
    name: "Rauriser Literaturtage",
    category: "kultur",
    region: "Pinzgau",
    months: [3],
    timing: "mehrere Tage Mitte/Ende März",
    url: "https://www.rauriser-literaturtage.at/",
    free: "ja",
    why: "Renommiertes Literaturfestival in einem Pinzgauer Bergdorf mit Nachwuchspreis – intime Lesungen und Debatten fernab des Betriebs.",
    note: "Kleiner Ort im Raurisertal – Anreise einplanen.",
  },
  {
    key: "gnigler-krampuslauf",
    name: "Gnigler Krampuslauf (Alt-Gnigler Pass)",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [11],
    timing: "Ende November rund um den Adventbeginn, abends",
    url: "https://www.altgnigler.at/",
    free: "ja",
    why: "Größter gewachsener Krampuslauf mitten in der Stadt (~10.000 Zuschauer) – echtes Brauchtum statt Touristen-Show, gratis am Straßenrand.",
  },
  {
    key: "fc-red-bull-salzburg-heimspiele",
    name: "FC Red Bull Salzburg – Heimspiele",
    category: "sport",
    region: "Flachgau",
    months: [8, 9, 10, 11, 12, 2, 3, 4, 5],
    timing: "Bundesliga-/Europacup-Saison August–Mai (Winterpause), Europacup vor allem im Herbst",
    url: "https://www.redbullsalzburg.at/",
    free: "nein",
    why: "Günstige Stehplätze, volle Red Bull Arena und internationale Europacup-Abende – Fixpunkt für junge Locals und sportbegeisterte Reisende.",
    note: "Red Bull Arena in Wals-Siezenheim (Flachgau); Spieltermine saisonal wechselnd – aktuellen Spielplan prüfen.",
  },
  {
    key: "ec-red-bull-salzburg-heimspiele",
    name: "EC Red Bull Salzburg – Eishockey-Heimspiele",
    category: "sport",
    region: "Stadt Salzburg",
    months: [9, 10, 11, 12, 1, 2, 3, 4],
    timing: "ICE-Hockey-League-Saison September bis Frühjahr (Play-offs)",
    url: "https://ecrbs.redbulls.com/",
    free: "nein",
    why: "Schnelles Eishockey in der stimmungsvollen Eisarena Volksgarten – günstiges, intensives Wintererlebnis mitten in der Stadt.",
    note: "Heimspieltermine saisonal wechselnd; Halle ~3.400 Plätze, oft ausverkauft.",
  },
  {
    key: "schmiede-hallein",
    name: "Schmiede Hallein",
    category: "kultur",
    region: "Tennengau",
    months: [9],
    timing: "rund zehn Tage Mitte/Ende September auf der Pernerinsel",
    url: "https://schmiedehallein.com/",
    free: "ja",
    why: "Internationales Prototyping-/Medienkunst-Festival auf der Pernerinsel – offener Kreativ-Spielplatz für die junge Kunst-, Tech- und Musikszene.",
    note: "Teilnahme per Bewerbung; öffentliche Präsentationen/Abende meist frei.",
  },
  {
    key: "european-street-food-festival-salzburg",
    name: "European Street Food Festival Salzburg",
    category: "party",
    region: "Stadt Salzburg",
    months: [6, 10],
    timing: "meist zweimal jährlich – ein Termin im Frühsommer, einer im Herbst",
    url: "https://www.streetfood-festival.eu/",
    free: "teils",
    why: "Streetfood aus aller Welt mit DJ-/Festivalstimmung im Volksgarten – lockeres, günstiges Ausgeh-Format für junge Foodies.",
    note: "Touring-Format, bespielt Salzburg mehrmals im Jahr; Eintritt oft frei, Speisen kostenpflichtig.",
  },
  {
    key: "balloonalps-zell-am-see-kaprun",
    name: "balloonalps – Alpin-Ballonwoche",
    category: "kultur",
    region: "Pinzgau",
    months: [1, 2],
    timing: "Ende Jänner/Anfang Februar, tägliche Starts am Morgen",
    url: "https://www.zellamsee-kaprun.com/",
    free: "teils",
    why: "Rund 20 Heißluftballons über der Hohe-Tauern-Kulisse plus „Nacht der Ballone“ – spektakuläres, gratis zu bestaunendes Winterschauspiel.",
    note: "Zuschauen frei, Ballonfahrten kostenpflichtig.",
  },
  {
    key: "bauernherbst-landeseroeffnung",
    name: "Salzburger Bauernherbst – Landeseröffnung",
    category: "tradition",
    region: "ganzes Land",
    months: [8],
    timing: "großes Eröffnungsfest Mitte/Ende August",
    url: "https://www.salzburgerland.com/de/bauernherbst/",
    free: "teils",
    why: "Zentrales Eröffnungsfest mit Festumzug, Tracht, Blasmusik und regionaler Kulinarik – authentisches Volksfest zum Saisonauftakt.",
    note: "NUR das konkrete Eröffnungsfest (Ort wechselt jährlich) – NICHT der Dachbegriff Bauernherbst.",
  },
  {
    key: "snow-jazz-gastein",
    name: "Snow Jazz Gastein",
    category: "kultur",
    region: "Pongau",
    months: [3],
    timing: "fünf Festivaltage Anfang März",
    url: "https://www.gastein.com/en/snow-jazz/",
    free: "teils",
    why: "Internationaler Jazz in Skihütten, Sägewerk und Hotels bis auf 2.200 m – Live-Musik plus Skifahren und Therme.",
  },
  {
    key: "salzburger-bergfilmfestival",
    name: "Salzburger Bergfilmfestival (DAS KINO)",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [11],
    timing: "rund zwei Wochen im November",
    url: "https://www.daskino.at/",
    free: "nein",
    why: "Abenteuer-, Berg- und Outdoor-Filme mit Vorträgen der Protagonist:innen – Fixtermin für die junge Berg-/Outdoor-Community.",
  },
  {
    key: "glocknerkoenig",
    name: "Glocknerkönig – Radrennen Großglockner Hochalpenstraße",
    category: "sport",
    region: "Pinzgau",
    months: [6],
    timing: "ein Samstag Anfang Juni, autofreie Bergstraße",
    url: "https://www.glocknerkoenig.com/",
    free: "teils",
    why: "Bergrennen die autofreie Glocknerstraße hinauf, offen ohne Lizenz – spektakulär zum Zuschauen und für ambitionierte Hobby-Radler zum Mitfahren.",
    note: "Start in Bruck; wetterabhängige Bergankunft.",
  },
  {
    key: "seefest-mattsee",
    name: "Seefest Mattsee",
    category: "party",
    region: "Flachgau",
    months: [7],
    timing: "letztes Juli-Wochenende (Fr/Sa), Seepromenade Mattsee",
    url: "https://www.mattsee.at/Seefest",
    free: "teils",
    why: "Lauschiges See-Clubbing am Mattsee mit DJs, Fire-Show und Klang-Feuerwerk – lauer Sommerabend am Wasser mit Freunden.",
    note: "Eintritt auf offizieller Seite nicht ausgewiesen; Seepromenade meist frei zugänglich.",
  },
  {
    key: "strobler-seefest",
    name: "Strobler Seefest am Wolfgangsee",
    category: "tradition",
    region: "Flachgau",
    months: [8],
    timing: "erstes August-Wochenende (Festumzug 18 Uhr, Synchron-Feuerwerk 22 Uhr)",
    url: "https://www.strobl.salzburg.at/Seefest",
    free: "ja",
    why: "Gratis Seefest am Wolfgangsee mit Trachten-Festumzug, Flaniermeile und Synchron-Klangfeuerwerk am Wasser – Brauchtum und Sommerparty in einem.",
    note: "Bei Regen Verschiebung auf den Folgetag.",
  },
  {
    key: "winzermarkt-salzburg",
    name: "Winzermarkt vor Schloss Mirabell",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [4, 5],
    timing: "mehrere Fr/Sa-Wochenenden im April und Mai am Mirabellplatz",
    url: "https://salzburg-altstadt.at/de/veranstaltungskalender/winzermarkt-2026",
    free: "ja",
    why: "Entspanntes Afterwork-Weintrinken bei österreichischen Winzer:innen mitten in der Stadt – Zutritt gratis, gezahlt wird nur das Glas.",
  },
  {
    key: "eat-meet-salzburg",
    name: "eat&meet – Kulinarik-Festival Altstadt",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [3],
    timing: "gesamter März (rund drei Wochen), Altstadt",
    url: "https://salzburg-altstadt.at/de/eat-meet",
    free: "teils",
    why: "Über 100 Genuss-Events in der Altstadt – Street-Food-Konzepte, Tastings und Crossover-Küche, ideal um die junge Foodszene kennenzulernen.",
    note: "Viele Programmpunkte kostenpflichtig, einzelne Formate offen.",
  },
  {
    key: "kunst-design-markt-salzburg",
    name: "kunst & design markt Salzburg",
    category: "kultur",
    region: "Stadt Salzburg",
    months: [3, 10],
    timing: "je ein Wochenende im Frühjahr (März) und Herbst (Oktober), Brandboxx",
    url: "https://kunst-designmarkt.at/salzburg/",
    free: "teils",
    why: "Rund 140 junge Designer:innen und Indie-Labels (Mode, Schmuck, Keramik, Grafik) – Pflichttermin für die kreative junge Szene.",
    note: "Eintritt ~5 €, Kinder unter 14 gratis; zweimal jährlich.",
  },
  {
    key: "salzburger-strassentheater",
    name: "Salzburger Straßentheater",
    category: "kultur",
    region: "ganzes Land",
    months: [7, 8],
    timing: "Anfang Juli bis Anfang August, ~42 Vorstellungen auf öffentlichen Plätzen",
    url: "https://www.kulturvereinigung.com/de/Strassentheater/Termine-2026",
    free: "ja",
    why: "Seit über 50 Jahren gratis Theater am Theaterwagen auf Plätzen in Stadt und Land – Kultur ohne Ticket-Hürde, spontan mitzunehmen.",
    note: "Freier Eintritt (Spenden erbeten).",
  },
  {
    key: "trumer-hopfenerntefest",
    name: "Trumer Hopfenerntefest",
    category: "party",
    region: "Flachgau",
    months: [9],
    timing: "ein Samstag Mitte September, Brauereigelände Obertrum",
    url: "https://www.trumer-erleben.at/",
    free: "teils",
    why: "Craft-Beer-Fest im Hopfengarten der Trumer Privatbrauerei mit Hopfenzupfen, Bieranstich, Beer-Bars, Foodtrucks und drei Live-Konzerten.",
    note: "Eintritt nicht ausgewiesen; nicht mit dem 'Trumer Bierfest' im Mai verwechseln.",
  },
  {
    key: "gasteiner-krampuslauf",
    name: "Gasteiner Krampuslauf",
    category: "tradition",
    region: "Pongau",
    months: [12],
    timing: "alljährlich 5. und 6. Dezember, ab ca. 16:30 in Bad Gastein, Bad Hofgastein und Dorfgastein",
    url: "https://www.gasteinertal.com/krampuslauf/",
    free: "ja",
    why: "Einer der größten und ursprünglichsten Krampusläufe Österreichs (80–100 Passen) – authentisches Alpen-Nachtspektakel als Tagestrip.",
    note: "Öffentlicher Straßenbrauch, Zuschauen gratis.",
  },
  {
    key: "krampuslauf-st-johann-obermarkt",
    name: "Krampuslauf im Obermarkt St. Johann im Pongau",
    category: "tradition",
    region: "Pongau",
    months: [12],
    timing: "rund um den 6. Dezember, abends im Obermarkt (Stadtzentrum)",
    url: "https://www.st.johann.at/Krampuslauf_im_Obermarkt",
    free: "ja",
    why: "Mit 500–600 Krampussen und tausenden Zuschauern eine der größten Krampusnächte des Landes – kostenloses Straßenspektakel mit Wucht.",
  },
  {
    key: "anifer-krampuslauf",
    name: "Anifer Krampuslauf",
    category: "tradition",
    region: "Flachgau",
    months: [12],
    timing: "5. Dezember, ca. 18:00 am Dorfplatz Anif",
    url: "https://www.anif.info/en/events/tradition/krampus/",
    free: "ja",
    why: "Direkt vor den Toren der Stadt (mit Bus erreichbar), ~5.000 Besucher – der am besten erreichbare Krampus-Einstieg fürs Stadtpublikum.",
  },
  {
    key: "rauriser-toifi-tag",
    name: "Rauriser Toifi (Toifi-Tag)",
    category: "tradition",
    region: "Pinzgau",
    months: [12],
    timing: "5. und 6. Dezember, Umzug am Nachmittag/Abend über den Marktplatz Rauris",
    url: "https://www.raurisertal.at/de/raurisertal/tradition-und-brauchtum",
    free: "ja",
    why: "'Tradition statt Show': unkommerzieller, nur im Raurisertal existierender Krampus-Brauch – die authentische, uninszenierte Erfahrung.",
    note: "Nicht verwechseln mit dem Rauriser PERCHTENlauf (6. Jänner), der nur biennal stattfindet.",
  },
  {
    key: "sonnwendfeuer-berge-in-flammen",
    name: "Sonnwendfeuer / Berge in Flammen",
    category: "tradition",
    region: "ganzes Land",
    months: [6],
    timing: "rund um die Sommersonnenwende (meist 20./21. Juni), Bergketten bei Nacht",
    url: "https://www.salzburgerland.com/de/magazin/berge-in-flammen-sonnwendfeuer-im-salzburgerland/",
    free: "ja",
    why: "Kostenlose Bergfeuer-Nacht zur Sonnwende (UNESCO-Kulturerbe) – Wandern, Feuer, Feiern; Schwerpunkt Pinzgau/Pongau.",
    note: "Einzelne Feuer können bei Waldbrandgefahr abgesagt werden.",
  },
  {
    key: "maxglaner-faschingsumzug",
    name: "Maxglaner Faschingsumzug",
    category: "tradition",
    region: "Stadt Salzburg",
    months: [2],
    timing: "Faschingszeit (meist Faschingssonntag), nachmittags durch Maxglan",
    url: "https://www.maxglaner-faschingsumzug.at/",
    free: "ja",
    why: "Größter Faschingsumzug der Stadt zum kostenlosen Mitgehen und Verkleiden – Straßenparty statt Ballkitsch, mitten in Salzburg.",
    note: "Genauer Termin variiert jährlich mit dem Faschingsdatum (Ende Jänner/Februar).",
  },
  {
    key: "histo-cup-salzburgring",
    name: "Histo Cup Salzburgring (Heimrennen)",
    category: "sport",
    region: "Flachgau",
    months: [9],
    timing: "Mitte/Ende September, dreitägiges Renn-Wochenende am Salzburgring",
    url: "https://www.histocup.com/renntermine/",
    free: "teils",
    why: "Größte historische Rennszene Zentraleuropas auf dem lokalen Traditionskurs – Motorsport-Klassiker mit Fahrerlager-Feeling für junge Petrolheads.",
    note: "Zuschauer-Tickets; Datum variiert leicht.",
  },
  {
    key: "gaisbergrennen-historisch",
    name: "Gaisbergrennen (historisch)",
    category: "sport",
    region: "Stadt Salzburg",
    months: [6],
    timing: "Anfang Juni, 3 Tage: City-Präsentation Residenzplatz + Bergstrecke Gaisberg",
    url: "https://www.src.co.at/gaisbergrennen-2/",
    free: "teils",
    why: "Historische Renn- und Sportwagen mitten in der Altstadt (Residenzplatz) und den Gaisberg hinauf – gratis anzuschauen, ein Fest für Autofans.",
    note: "Gleichmäßigkeitslauf (kein echtes Rennen), Fahrzeuge bis Bj. 1979.",
  },
  {
    key: "weltkindertag-salzburg",
    name: "Weltkindertag Salzburg",
    category: "kids",
    region: "Stadt Salzburg",
    months: [9],
    timing: "letzter Freitag im September, nachmittags offen für alle (wechselnde Orte)",
    url: "https://www.kinderrechte-salzburg.at/in-salzburg/",
    free: "ja",
    why: "Kostenloses stadtweites Kinder- und Familienfest mit Workshops (bis Graffiti und Käfig-Fußball) – füllt die dünn besetzte kids-Kategorie.",
    note: "Veranstaltungsort wechselt jährlich.",
  },
];

// Anker, deren typisches Zeitfenster einen der übergebenen Monate berührt.
// (Wird in der Wochenrecherche nach dem Monat der Zielwoche gefiltert -> token-schlau.)
export function anchorsForMonths(months: number[]): AnchorEvent[] {
  const set = new Set(months);
  return ANCHOR_EVENTS.filter((a) => a.months.some((m) => set.has(m)));
}
