-- ============================================================================
-- SalzGuide — Event-Anker (jährliche „Pflicht-Highlights" im Land Salzburg)
-- Zweck: ERINNERUNG/Checkliste für die KI-Wochenrecherche, damit kein großes
-- jährliches Event übersehen wird. Enthält KEINE konkreten Datteln (nur Monats-
-- Zeitfenster + offizielle Quelle) — Datum/Uhrzeit werden pro Woche live verifiziert.
-- Über das Admin-Panel pflegbar (kein Code-Deploy nötig).
-- Idempotent: kann gefahrlos mehrfach ausgeführt werden. Im Supabase SQL-Editor ausführen.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tabelle (nutzt das bestehende enum event_category aus 0009_events.sql)
-- ----------------------------------------------------------------------------
create table if not exists public.event_anchors (
  id          uuid primary key default gen_random_uuid(),
  key         text unique not null,          -- stabiler slug (z.B. "electric-love")
  name        text not null,
  category    event_category not null default 'kultur',
  region      text not null default 'ganzes Land',
  months      int[] not null default '{}',   -- Monate (1–12), in denen es typisch läuft
  timing      text not null default '',       -- Zeitfenster in Worten (KEIN Beleg)
  url         text not null default '',       -- offizielle Quelle zum Verifizieren
  free        text not null default 'nein' check (free in ('ja','nein','teils')),
  why         text not null default '',       -- 1 Satz: warum für die Zielgruppe wichtig
  note        text,                           -- Vorbehalt (z.B. „nur alle 2 Jahre")
  active      boolean not null default true,  -- im Admin an-/abschaltbar
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.event_anchors is
  'Jährliche Anker-Events: Erinnerung für die KI-Wochenrecherche. Nur Zeitfenster + Quelle, KEINE festen Datteln — die werden pro Woche live verifiziert.';
comment on column public.event_anchors.months is
  'Monate 1–12, in denen das Event typischerweise stattfindet -> Filter für die Zielwoche.';

create index if not exists event_anchors_active_idx on public.event_anchors (active);

-- updated_at pflegen (Funktion aus 0001_init.sql)
drop trigger if exists event_anchors_set_updated_at on public.event_anchors;
create trigger event_anchors_set_updated_at
  before update on public.event_anchors
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 2. Row Level Security (Default deny; nur Admin liest/schreibt via UI).
--    Die KI-Wochenrecherche liest über den service_role-Key (umgeht RLS).
-- ----------------------------------------------------------------------------
alter table public.event_anchors enable row level security;

drop policy if exists "event_anchors_admin_all" on public.event_anchors;
create policy "event_anchors_admin_all" on public.event_anchors
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ----------------------------------------------------------------------------
-- 3. Seed (idempotent: on conflict (key) do nothing -> überschreibt Admin-Edits NIE)
--    >>> Wird weiter unten in diesem File eingefügt (aus event-anchors.ts generiert). <<<
-- ----------------------------------------------------------------------------
insert into public.event_anchors
  (key, name, category, region, months, timing, url, free, why, note, active, sort_order)
values
  ('salzburger-festspiele', 'Salzburger Festspiele', 'kultur', 'Stadt Salzburg', '{7,8}', 'meist Mitte Juli–Ende August (dazu Pfingstfestspiele Ende Mai)', 'https://www.salzburgerfestspiele.at/', 'nein', 'Weltgrößtes Klassik-/Theaterfestival vor der Haustür – Jedermann, Oper, Weltstars, plus viel Gratis-Randprogramm.', null, true, 0),
  ('siemens-festspiel-naechte', 'Siemens Fest>Spiel>Nächte', 'kultur', 'Stadt Salzburg', '{7,8}', 'während der Festspiele, täglich am Kapitelplatz', 'https://www.siemens.com/at/de/unternehmen/stories/fest-spiel-naechte.html', 'ja', 'Gratis Opern-/Konzert-Public-Viewing auf Riesen-LED-Wand mit Festungsblick – Festspiel-Feeling ohne Ticketpreis.', null, true, 1),
  ('jung-und-jeder', 'jung & jede*r (Festspiele-Jugendprogramm)', 'kultur', 'Stadt Salzburg', '{7,8}', 'Hauptprogramm während der Sommerfestspiele (Juli/August)', 'https://www.salzburgerfestspiele.at/jung-jeder', 'teils', 'Bis zu 90 % Rabatt für unter 27-Jährige plus gratis Mitmach-Formate – günstigster Zugang zu den Festspielen.', null, true, 2),
  ('mozartwoche', 'Mozartwoche', 'kultur', 'Stadt Salzburg', '{1}', 'Ende Jänner rund um Mozarts Geburtstag', 'https://mozarteum.at/mozartwoche', 'nein', 'Dichteste Mozart-Woche der Welt in seiner Geburtsstadt – Weltklasse-Ensembles, dazu Kino & Pub-Quiz.', null, true, 3),
  ('sommerszene', 'Sommerszene (SZENE Salzburg)', 'kultur', 'Stadt Salzburg', '{6}', 'meist Juni', 'https://www.szene-salzburg.net/sommerszene', 'nein', 'Internationaler zeitgenössischer Tanz & Performance – das avantgardistische Gegenprogramm zur Klassik-Stadt.', null, true, 4),
  ('jazz-and-the-city', 'Jazz&TheCity', 'kultur', 'Stadt Salzburg', '{10}', 'Mitte Oktober', 'https://salzburg-altstadt.at/de/salzburgjazz', 'ja', '~80 Gratis-Konzerte (Jazz, Global Groove, Electronic) in Clubs & Höfen der Altstadt – Festival-Hopping ohne Ticket.', null, true, 5),
  ('live-in-salzburg', 'Live in Salzburg', 'party', 'Stadt Salzburg', '{7,8}', 'Open-Air-Konzerttage im Volksgarten, meist Ende August', 'https://www.stadt-salzburg.at/liveinsalzburg', 'ja', 'Gratis Open-Air-Konzerte, DJ-Contest & Sommerkino im Volksgarten – das kostenlose Sommer-Line-up der Stadt.', null, true, 6),
  ('sternenkino-salzburg', 'Sternenkino Salzburg', 'kultur', 'Stadt Salzburg', '{6,7}', 'Ende Juni–Anfang Juli, Open-Air am Kapitelplatz', 'https://sternenkino-salzburg.at/', 'ja', 'Gratis Open-Air-Kino am Kapitelplatz mit Festungsblick – Klassiker & Newcomer in lauen Sommernächten.', null, true, 7),
  ('pride-festival-salzburg', 'Pride Festival Salzburg (vormals CSD)', 'kultur', 'Stadt Salzburg', '{8,9}', 'Ende August–Anfang September, Parade meist Anfang September', 'https://www.queersalzburg.at/', 'teils', 'Zehn Tage buntes queeres Programm mit ~30 Events, großer Pride-Parade und Pride-Night in der ARGEkultur.', null, true, 8),
  ('rupertikirtag', 'Salzburger Rupertikirtag', 'tradition', 'Stadt Salzburg', '{9}', 'Ende September rund um den Rupertitag (24.9.)', 'https://www.salzburg-altstadt.at/de/rupertikirtag', 'ja', 'Größter Altstadt-Kirtag mit 120+ Attraktionen, Fahrgeschäften & Standln über die Domplätze – Volksfest mitten in der Stadt.', null, true, 9),
  ('salzburger-dult', 'Salzburger Dult', 'tradition', 'Stadt Salzburg', '{5}', 'Frühlings-Volksfest rund um Pfingsten im Mai (Messezentrum)', 'https://www.dult.at/de/', 'ja', 'Westösterreichs größtes Volksfest mit Vergnügungspark, Dult-Stadl, Live-Musik & Clubbings – gratis Eintritt.', null, true, 10),
  ('stadtfest-salzburg', 'Stadtfest Salzburg', 'party', 'Stadt Salzburg', '{6}', 'Wochenende Ende Juni, Altstadt', 'https://stadtfest-salzburg.at/', 'ja', 'Autofreie Open-Air-Bühne mit ~25 Bühnen, Live-Bands, DJs & Streetfood – jung, gratis, mittendrin.', null, true, 11),
  ('christkindlmarkt-salzburg', 'Salzburger Christkindlmarkt (Dom-/Residenzplatz)', 'tradition', 'Stadt Salzburg', '{11,12,1}', 'Advent bis Neujahr', 'https://christkindlmarkt.co.at/', 'ja', 'Klassischer Adventmarkt vor dem Dom mit Punsch, Turmblasen, Chören & Krampusläufen – der Weihnachtstreffpunkt der Stadt.', 'Dauer-Markt: NICHT pro Tag listen – nur konkrete Termine/Specials (Turmblasen, Krampuslauf) oder 1× als ganztägiger Hinweis.', true, 12),
  ('hellbrunner-adventzauber', 'Hellbrunner Adventzauber', 'tradition', 'Stadt Salzburg', '{11,12}', 'Advent bis Heiligabend, Schloss Hellbrunn', 'https://www.hellbrunneradventzauber.at/', 'teils', 'Stimmungsvoller Adventmarkt am Schloss mit riesigem Christbaum – abends gratis, sonst mit Getränkegutschein.', 'Dauer-Markt: NICHT pro Tag listen.', true, 13),
  ('sternadvent-salzburg', 'Sternadvent (Sternarkaden)', 'tradition', 'Stadt Salzburg', '{11,12,1}', 'Advent bis Dreikönig, Sternarkaden der Altstadt', 'https://www.sternadvent.at/', 'ja', 'Kuratierter, feiner Adventmarkt in den Sternarkaden – kleiner und weniger touristisch als die Domplätze.', 'Dauer-Markt: NICHT pro Tag listen.', true, 14),
  ('winterfest-salzburg', 'Winterfest – Festival für zeitgenössischen Zirkus', 'kultur', 'Stadt Salzburg', '{11,12,1}', 'Advent bis Dreikönig, Zeltstadt im Volksgarten', 'https://www.winterfest.at/', 'nein', 'Größtes Festival für Neuen Circus im deutschsprachigen Raum – die richtig gute Alternative zum Adventmarkt.', null, true, 15),
  ('electric-love', 'Electric Love Festival', 'party', 'Flachgau', '{7}', 'Anfang/Mitte Juli (Do–Sa), Salzburgring Plainfeld', 'https://www.electriclove.at/', 'nein', 'Österreichs größtes EDM-Festival mit Weltklasse-DJs & gewaltiger Mainstage – der Party-Fixpunkt des Sommers.', null, true, 16),
  ('jazzfestival-saalfelden', 'Jazzfestival Saalfelden', 'kultur', 'Pinzgau', '{8,1}', 'Haupt: Ende August; zusätzlich Winter-Edition im Jänner', 'https://www.jazzsaalfelden.com/', 'teils', 'Weltklasse-Jazz & Avantgarde mit vielen kostenlosen Open-Air-Bühnen in der Stadt und Sessions in den Bergen.', null, true, 17),
  ('bergfestival-saalbach', 'BERGFESTival Saalbach', 'party', 'Pinzgau', '{12}', 'Anfang Dezember (Fr–So), Saalbach-Hinterglemm', 'https://www.berg-festival.com/', 'nein', 'Ski, Après-Ski & Live-Bands (Punk/Ska/Indie/Brass) auf dem Berg – Winterurlaub und Festival in einem.', null, true, 18),
  ('rave-on-snow', 'Rave On Snow', 'party', 'Pinzgau', '{12}', 'Mitte Dezember (Do–So), Saalbach-Hinterglemm', 'https://raveonsnow.com/', 'nein', 'Elektro-Winterrave mit 70+ DJs auf bis zu 12 Floors – tagsüber Ski, nachts durchtanzen in Alpenkulisse.', null, true, 19),
  ('mtb-weltcup-leogang', 'UCI Mountainbike Weltcup Leogang', 'kultur', 'Pinzgau', '{6}', 'meist Mitte Juni, ein Wochenende, Bikepark Leogang', 'https://www.mtb-weltcup.at/en', 'teils', 'Weltklasse-Downhill & Cross-Country im Bikepark Leogang – actionreiches Sommer-Highlight für ein junges Publikum.', null, true, 20),
  ('salzburg-trailrunning-festival', 'Salzburg Trailrunning Festival', 'kultur', 'Stadt Salzburg', '{10}', 'meist letztes Oktober-Wochenende (Nightrun über Festung & Gaisberg)', 'https://www.trailrunning-festival.at/de/', 'teils', 'Urbanes Trail-Festival mit Nachtlauf über Festung und Gaisberg – Zuschauen gratis.', null, true, 21),
  ('nachtslalom-flachau', 'FIS Ski-Weltcup Damen-Nachtslalom Flachau', 'kultur', 'Pongau', '{1}', 'Damen-Nachtslalom unter Flutlicht, Anfang/Mitte Jänner', 'https://www.skiweltcup-flachau.at/', 'nein', 'Flutlicht-Nachtslalom mit Après-Ski-Stimmung & Ö3-DJ – die lauteste Weltcup-Party im Land.', null, true, 22),
  ('vierschanzentournee-bischofshofen', 'Vierschanzentournee Bischofshofen (Dreikönigsspringen)', 'kultur', 'Pongau', '{1}', 'immer am Dreikönigstag (6. Jänner)', 'https://www.vierschanzentournee.com/bischofshofen/', 'nein', 'Das große Skisprung-Finale der Tournee mit ~25.000 Fans – Gänsehaut-Event zum Jahresauftakt.', null, true, 23),
  ('ski-weltcup-zauchensee', 'FIS Ski-Weltcup Damen Zauchensee (Speed)', 'kultur', 'Pongau', '{1}', 'Damen-Abfahrt/Super-G, meist Mitte Jänner', 'https://www.zauchensee.at/de/audi-fis-ski-weltcup-altenmarkt-zauchensee.html', 'teils', 'Damen-Speed-Klassiker auf der Kälberloch-Abfahrt – hochkarätiger Weltcup in Ski amadé.', 'NICHT jährlich – nur alle 2 Jahre (biennal); in vielen Saisonen NICHT im Kalender. Vorab prüfen, ob heuer Austragungsjahr.', true, 24),
  ('snowboard-weltcup-gastein', 'FIS Snowboard-Alpin-Weltcup Bad Gastein', 'kultur', 'Pongau', '{1}', 'Parallelslalom unter Flutlicht, Mitte Jänner', 'https://www.gasteinertal.com/snowboard-weltcup/', 'ja', 'Flutlicht-Parallelslalom mitten im Ort mit Live-Musik & After-Race-Party – gratis, jung, Snowboard statt Ski.', 'Snowboard-Weltcup (NICHT der klassische Ski-Weltcup).', true, 25),
  ('winter-opening-flachau', 'Winter Opening Flachau (Ski-Opening mit Konzert)', 'party', 'Pongau', '{12}', 'Saisoneröffnung mit gratis Open-Air-Konzert, erstes Dezember-Wochenende', 'https://www.flachau.com/', 'ja', 'Saisonauftakt mit gratis Open-Air-Konzert (zuletzt Gabalier, DJ Ötzi, Nockis) – Partystart in den Winter.', null, true, 26),
  ('art-on-snow-gastein', 'Art on Snow Gastein', 'kultur', 'Pongau', '{1,2}', 'Schnee-/Eiskunst-Festival, Ende Jänner–Anfang Februar', 'https://www.gasteinertal.com/art-on-snow/', 'teils', 'Eines der größten Schnee-/Eiskunst-Festivals der Alpen – begehbare Skulpturenwelt im ganzen Tal.', null, true, 27),
  ('ironman-703-zell-am-see', 'IRONMAN 70.3 Zell am See-Kaprun', 'kultur', 'Pinzgau', '{8}', 'Halbdistanz-Triathlon, meist Ende August', 'https://www.zellamsee-kaprun.com/en/events/ironman', 'teils', 'Triathlon-Spektakel mit Schwimmen im Zeller See vor Gletscher-Kulisse – Zuschauen gratis.', null, true, 28),
  ('mozart-100-utmb', 'mozart 100 by UTMB (Salzburg Ultra Trail)', 'kultur', 'Flachgau', '{5}', 'Ultra-Trail (12–120 km), meist Ende Mai, Fuschlseeregion', 'https://mozart.utmb.world/', 'teils', 'UTMB-Ultratrail rund um Fuschl- und Wolfgangsee – Distanzen für Einsteiger bis Ultra.', null, true, 29),
  ('stadtfest-hallein', 'Stadtfest Hallein', 'party', 'Tennengau', '{6}', 'ein Tag Ende Juni, Altstadt Hallein', 'https://www.hallein.com/', 'ja', 'Urbanes Ein-Tages-Festival mit freiem Eintritt & internationalem Line-up – das Party-Highlight im Tennengau.', null, true, 30),
  ('krampuslauf-hallein', 'Halleiner Krampuslauf (Igonta Pass)', 'tradition', 'Tennengau', '{11,12}', 'immer am 1. Adventsonntag, Altstadt Hallein', 'https://www.hallein.com/', 'ja', 'Einer der größten Krampusläufe des Landes mit 600+ Krampussen durch die enge Altstadt – Gänsehaut pur.', null, true, 31),
  ('krampuslauf-grossgmain', 'Krampuslauf Großgmain', 'tradition', 'Flachgau', '{12}', 'um den 5. Dezember (Nikolaus-Vorabend), abends', 'https://www.grossgmain.at/', 'ja', 'Bekannter Flachgauer Krampuslauf mit allen Passen & Party – Brauchtum direkt an der Stadtgrenze.', null, true, 32),
  ('pongauer-perchtenlauf', 'Großer Pongauer Perchtenlauf', 'tradition', 'Pongau', '{12,1}', 'in den Rauhnächten (21. Dezember–6. Jänner)', 'https://www.gauverband-pongau.at/', 'ja', 'Größter Perchtenlauf im Land mit ~400 Mitwirkenden (Schön- & Schiachperchten) – archaisches Jahreswechsel-Brauchtum.', 'Austragungsort ROTIERT jährlich (Altenmarkt / Bischofshofen / Gastein / St. Johann) – Ort & Termin vorab prüfen.', true, 33),
  ('samson-umzuege-lungau', 'Samsonumzüge im Lungau', 'tradition', 'Lungau', '{6,7,8,9}', 'mehrere Festtage im Sommer/Frühherbst, ~10 Lungauer Orte', 'https://www.salzburgerland.com/de/magazin/samsonumzuege-riesen-im-lungau-unterwegs/', 'ja', 'Bis zu 7 m hohe, tanzende Riesenfiguren durch die Dörfer – UNESCO-Kulturerbe, eines der spektakulärsten Brauchtümer.', 'Mehrere Orte & Termine (Tamsweg, Mauterndorf, St. Andrä …) – konkreten Ort/Termin prüfen.', true, 34),
  ('prangstangen-lungau', 'Prangstangen-Prozession Zederhaus & Muhr', 'tradition', 'Lungau', '{6}', 'Zederhaus am 24. Juni, Muhr am 29. Juni', 'https://www.muhr-tourismus.at/brauchtum/prangstangen/', 'ja', '6–8 m hohe, mit zehntausenden Blumen umwundene Stangen (~85 kg) – einzigartiges Lungauer UNESCO-Brauchtum.', null, true, 35),
  ('maibaum-salzburg', 'Maibaumaufstellen', 'tradition', 'ganzes Land', '{4,5}', 'rund um den 1. Mai (teils Vorabend 30. April), fast jede Gemeinde', 'https://www.salzburgerland.com/de/', 'ja', 'Muskelkraft, Blasmusik & Bier: gemeinsames Aufstellen des geschmückten Maibaums – der geselligste Frühlings-Brauch.', 'Kein einzelnes Hauptfest – konkretes, benanntes Gemeinde-Maifest mit Datum/Uhrzeit suchen.', true, 36),
  ('seefest-zell-am-see', 'Seefest Zell am See', 'tradition', 'Pinzgau', '{7,8}', 'zwei Termine im Hochsommer (Air-/Wassershow, Feuerwerk)', 'https://www.zellerseefest.at/', 'teils', 'Größtes Seefest im Pinzgau mit Flying-Bulls-Airshow, Live-Musik & Feuerwerk über dem See – Sommerabend-Tradition.', null, true, 37),
  ('almabtrieb-maishofen', 'Almabtrieb & Hoffest Kammererbauer Maishofen', 'tradition', 'Pinzgau', '{9}', 'Bauernherbst, meist Mitte/Ende September bei Schloss Kammer', 'https://www.maishofen.com/', 'ja', 'Geschmücktes Vieh zieht von der Alm ins Tal, Hoffest mit Musik & Schmankerln – ein konkreter Almabtrieb statt Bauernherbst-Slogan.', null, true, 38),
  ('silvester-altstadt-salzburg', 'Silvester in der Salzburger Altstadt', 'tradition', 'Stadt Salzburg', '{12,1}', 'Silvesternacht 31. Dezember, Ausklang am Neujahrstag', 'https://www.salzburg.info/de/salzburg/silvester', 'ja', 'Gratis Open-Air mit Live-Bands, Feuerwerk von der Festung und dem großen Neujahrswalzer am Domplatz – Treffpunkt statt teurem Club.', 'Privates Feuerwerk/Böller im Stadtgebiet verboten; öffentlicher Platz, kein Ticket.', true, 39),
  ('stille-nacht-gedenkfeier-oberndorf', 'Stille-Nacht-Gedenkfeier Oberndorf', 'tradition', 'Flachgau', '{12}', 'Heiliger Abend, 24. Dezember am späten Nachmittag', 'https://www.oberndorf.salzburg.at/Traditionelle_Stille-Nacht-Gedenkfeier', 'ja', 'Weltberühmte, gratis Gedenkfeier vor der Stille-Nacht-Kapelle – ein stimmungsvolles Ritual am 24.12., das man einmal live erlebt haben sollte.', 'Sehr besinnlich, kein Party-Format; wird auch per Livestream übertragen.', true, 40),
  ('aperschnalzen-rupertigau', 'Aperschnalzen / Rupertigau-Preisschnalzen', 'tradition', 'Flachgau', '{1,2}', 'zwischen Dreikönig und Faschingsdienstag (Jänner/Februar)', 'https://www.schnalzen.de/termine/', 'ja', 'Lautes, archaisches Winterbrauchtum (Goaßl-Schnalzen zum Winteraustreiben) im Flachgau – gratis am Dorfplatz, ohne Touristen-Inszenierung.', 'Dezentraler, grenzüberschreitender Brauch (Flachgau + Rupertiwinkel); großes Preisschnalzen an wechselnden Orten.', true, 41),
  ('lange-nacht-der-museen-salzburg', 'ORF-Lange Nacht der Museen', 'kultur', 'ganzes Land', '{10}', 'erstes Oktober-Wochenende, Samstagabend bis Mitternacht', 'https://langenacht.orf.at/state/bl/salzburg', 'nein', 'Ein Ticket, dutzende Museen & Galerien bis Mitternacht plus Shuttle – günstiger Kultur-Marathon für einen Abend mit Freunden.', 'Bundesweites Sammelticket; Schwerpunkt Stadt Salzburg.', true, 42),
  ('lange-nacht-der-kirchen-salzburg', 'Lange Nacht der Kirchen', 'kultur', 'ganzes Land', '{6}', 'ein Freitagabend Anfang Juni', 'https://www.langenachtderkirchen.at/dioezesen-seiten/salzburg/', 'ja', 'Gratis Konzerte, Lesungen, Turmbesteigungen und Nachtführungen an sonst geschlossenen Orten – kulturelle Entdeckungstour, längst über Religion hinaus.', 'Landesweit rund 50 Standorte.', true, 43),
  ('salzburg-marathon', 'Salzburg Marathon (Lauffestspiele)', 'kultur', 'Stadt Salzburg', '{5}', 'ein Mai-Wochenende (Nightrun Samstag, Hauptläufe Sonntag)', 'https://salzburg-marathon.at/', 'teils', 'Lauffest quer durch die Altstadt mit Start auf der Staatsbrücke – Zuschauen gratis, Distanzen vom Nightrun bis Marathon.', 'Selbes Wochenende: Salzburger Frauenlauf und Nightrun als eigene Bewerbe.', true, 44),
  ('trumer-triathlon', 'Trumer Triathlon', 'kultur', 'Flachgau', '{7}', 'ein Juli-Wochenende (Fr–So) am Trumer See', 'https://www.trumer-triathlon.at/', 'teils', 'Sommerlicher Seen-Triathlon im Salzburger Seenland mit Volksfest-Stimmung an der Strecke – Zuschauen gratis, auch zum Mitmachen.', 'Sieben Bewerbe inkl. Kinder- und Funtriathlon.', true, 45),
  ('wolfgangseelauf', 'Internationaler Wolfgangseelauf', 'kultur', 'Flachgau', '{10}', 'drittes Oktober-Wochenende rund um den Wolfgangsee', 'https://www.wolfgangseelauf.at/', 'teils', 'Österreichs größter Landschaftslauf einmal rund um den See – riesige Kulisse, Zuschauen gratis, Bewerbe von 5 km bis Marathon.', 'Grenzüberschreitend: Start/Ziel St. Gilgen (Flachgau), Teil über St. Wolfgang (OÖ).', true, 46),
  ('literaturfest-salzburg', 'Literaturfest Salzburg', 'kultur', 'Stadt Salzburg', '{5}', 'fünf Tage im Mai, über die ganze Stadt verteilt', 'https://www.literaturfest-salzburg.at/', 'teils', 'Lesungen, literarische Spaziergänge und Performances an ungewöhnlichen Orten – lockeres, stadtweites Literaturfestival statt steifer Hochkultur.', null, true, 47),
  ('rauriser-literaturtage', 'Rauriser Literaturtage', 'kultur', 'Pinzgau', '{3}', 'mehrere Tage Mitte/Ende März', 'https://www.rauriser-literaturtage.at/', 'teils', 'Renommiertes Literaturfestival in einem Pinzgauer Bergdorf mit Nachwuchspreis – intime Lesungen und Debatten fernab des Betriebs.', 'Kleiner Ort im Raurisertal – Anreise einplanen.', true, 48),
  ('gnigler-krampuslauf', 'Gnigler Krampuslauf (Alt-Gnigler Pass)', 'tradition', 'Stadt Salzburg', '{11}', 'Ende November rund um den Adventbeginn, abends', 'https://www.altgnigler.at/', 'ja', 'Größter gewachsener Krampuslauf mitten in der Stadt (~10.000 Zuschauer) – echtes Brauchtum statt Touristen-Show, gratis am Straßenrand.', null, true, 49),
  ('fc-red-bull-salzburg-heimspiele', 'FC Red Bull Salzburg – Heimspiele', 'kultur', 'Flachgau', '{8,9,10,11,12,2,3,4,5}', 'Bundesliga-/Europacup-Saison August–Mai (Winterpause), Europacup vor allem im Herbst', 'https://www.redbullsalzburg.at/', 'nein', 'Günstige Stehplätze, volle Red Bull Arena und internationale Europacup-Abende – Fixpunkt für junge Locals und sportbegeisterte Reisende.', 'Red Bull Arena in Wals-Siezenheim (Flachgau); Spieltermine saisonal wechselnd – aktuellen Spielplan prüfen.', true, 50),
  ('ec-red-bull-salzburg-heimspiele', 'EC Red Bull Salzburg – Eishockey-Heimspiele', 'kultur', 'Stadt Salzburg', '{9,10,11,12,1,2,3,4}', 'ICE-Hockey-League-Saison September bis Frühjahr (Play-offs)', 'https://ecrbs.redbulls.com/', 'nein', 'Schnelles Eishockey in der stimmungsvollen Eisarena Volksgarten – günstiges, intensives Wintererlebnis mitten in der Stadt.', 'Heimspieltermine saisonal wechselnd; Halle ~3.400 Plätze, oft ausverkauft.', true, 51),
  ('schmiede-hallein', 'Schmiede Hallein', 'kultur', 'Tennengau', '{9}', 'rund zehn Tage Mitte/Ende September auf der Pernerinsel', 'https://schmiedehallein.com/', 'teils', 'Internationales Prototyping-/Medienkunst-Festival auf der Pernerinsel – offener Kreativ-Spielplatz für die junge Kunst-, Tech- und Musikszene.', 'Teilnahme per Bewerbung; öffentliche Präsentationen/Abende meist frei.', true, 52),
  ('open-mind-festival-argekultur', 'Open Mind Festival (ARGEkultur)', 'kultur', 'Stadt Salzburg', '{11}', 'Herbst, traditionell im November, in der ARGEkultur', 'https://www.argekultur.at/', 'teils', 'Diskursives Festival zu Gesellschaft & Zukunft mit Performance, Musik und Debatte – Treffpunkt der jungen, politisch interessierten Szene.', 'Zuletzt zu einer über den Herbst verteilten Reihe umgebaut – Timing kann variieren.', true, 53),
  ('european-street-food-festival-salzburg', 'European Street Food Festival Salzburg', 'party', 'Stadt Salzburg', '{6,10}', 'meist zweimal jährlich – ein Termin im Frühsommer, einer im Herbst', 'https://www.streetfood-festival.eu/', 'teils', 'Streetfood aus aller Welt mit DJ-/Festivalstimmung im Volksgarten – lockeres, günstiges Ausgeh-Format für junge Foodies.', 'Touring-Format, bespielt Salzburg mehrmals im Jahr; Eintritt oft frei, Speisen kostenpflichtig.', true, 54),
  ('balloonalps-zell-am-see-kaprun', 'balloonalps – Alpin-Ballonwoche', 'kultur', 'Pinzgau', '{1,2}', 'Ende Jänner/Anfang Februar, tägliche Starts am Morgen', 'https://www.zellamsee-kaprun.com/', 'teils', 'Rund 20 Heißluftballons über der Hohe-Tauern-Kulisse plus „Nacht der Ballone“ – spektakuläres, gratis zu bestaunendes Winterschauspiel.', 'Zuschauen frei, Ballonfahrten kostenpflichtig.', true, 55),
  ('bauernherbst-landeseroeffnung', 'Salzburger Bauernherbst – Landeseröffnung', 'tradition', 'ganzes Land', '{8}', 'großes Eröffnungsfest Mitte/Ende August', 'https://www.salzburgerland.com/de/bauernherbst/', 'teils', 'Zentrales Eröffnungsfest mit Festumzug, Tracht, Blasmusik und regionaler Kulinarik – authentisches Volksfest zum Saisonauftakt.', 'NUR das konkrete Eröffnungsfest (Ort wechselt jährlich) – NICHT der Dachbegriff Bauernherbst.', true, 56),
  ('snow-jazz-gastein', 'Snow Jazz Gastein', 'kultur', 'Pongau', '{3}', 'fünf Festivaltage Anfang März', 'https://www.gastein.com/en/snow-jazz/', 'teils', 'Internationaler Jazz in Skihütten, Sägewerk und Hotels bis auf 2.200 m – Live-Musik plus Skifahren und Therme.', null, true, 57),
  ('salzburger-bergfilmfestival', 'Salzburger Bergfilmfestival (DAS KINO)', 'kultur', 'Stadt Salzburg', '{11}', 'rund zwei Wochen im November', 'https://www.daskino.at/', 'nein', 'Abenteuer-, Berg- und Outdoor-Filme mit Vorträgen der Protagonist:innen – Fixtermin für die junge Berg-/Outdoor-Community.', null, true, 58),
  ('glocknerkoenig', 'Glocknerkönig – Radrennen Großglockner Hochalpenstraße', 'kultur', 'Pinzgau', '{6}', 'ein Samstag Anfang Juni, autofreie Bergstraße', 'https://www.glocknerkoenig.com/', 'teils', 'Bergrennen die autofreie Glocknerstraße hinauf, offen ohne Lizenz – spektakulär zum Zuschauen und für ambitionierte Hobby-Radler zum Mitfahren.', 'Start in Bruck; wetterabhängige Bergankunft.', true, 59)
on conflict (key) do nothing;
